Add team DJs
langjam/jam0001 pull request #115
Opened 2021-08-21 12:34 UTC by tanguy-a

2021-08-21 17:25 UTC, jntrnr requested changes
Instead of adding the binaries directly to the repo, can you add links to where to download them?

This will keep the repo a bit smaller. Also, it's good practice not to have raw executables in the repo.

2021-08-22 02:23 UTC, jntrnr commented
Please remove the executables.

2021-08-22 08:44 UTC, tanguy-a commented
> Instead of adding the binaries directly to the repo, can you add links to where to download them?
> 
> This will keep the repo a bit smaller. Also, it's good practice not to have raw executables in the repo.

Sure i'm doing that.

2021-08-22 16:59 UTC, jntrnr approved these changes

2021-08-22 18:03 UTC, merged